### ISSUE TITLE
Update page title

### ISSUE THREAD

**Issue by omerozturkh** [omergulen/producthunt-trending-extension#7]
I think need update page title :) looks like empty tab. Sometimes i forget and close empty tabs. Thanks.
<img width="151" alt="Screen Shot 2019-08-22 at 15 05 11" src="https://user-images.githubusercontent.com/3657764/63513260-635fe400-c4ee-11e9-95aa-78348533f44b.png">

**Comment by omergulen** [comment]
It really is an empty tab tho xd
