### ISSUE TITLE
The text overfills the dropdown menu of choosing the time interval for trending products.

### ISSUE THREAD

**Issue by iremlaya** [omergulen/producthunt-trending-extension#8]
Such as this: 
![image](https://user-images.githubusercontent.com/39283781/63591910-dc2b7280-c5b8-11e9-9351-9ab908265e8a.png)

There are few solutions to tackle this. It's a minor problem but an issue nonetheless :)

**Comment by omergulen** [comment]
It works fine in my tests, can you please give more details about your screen res., browser, OS and relevant other stuff?

**Comment by iremlaya** [comment]
15.6 inch 16:9, 1920 x 1080 pixel  with 125%, 141 PPI
Windows 10
Brave Browser

**Comment by omergulen** [comment]
Please try making scaling 100% first.
